export const upgrades = [
    { lifes: 1 },
    { lifes: 3 },
    { lifes: 5 },
    { lifes: 8 },
    { lifes: 10 },
    { lifes: 15 },
    { lifes: 25 },

    { damage: 1 },
    { damage: 3 },
    { damage: 5 },
    { damage: 8 },
    { damage: 10 },
    { damage: 15 },
    { damage: 25 },

    { lifes: 1, damage: 25 },
    { lifes: 3, damage: 15 },
    { lifes: 5, damage: 10 },
    { lifes: 8, damage: 8 },
    { lifes: 10, damage: 5 },
    { lifes: 15, damage: 3 },
    { lifes: 25, damage: 1 },

    { lifes: -1, damage: -3 },
    { lifes: -3, damage: -5 },
    { lifes: -5, damage: -10 },
    { lifes: -10, damage: -8 },
]